### ISSUE TITLE
issue with on_connect command

### ISSUE THREAD

**Issue by Hecot** [pradeesi/Store_MQTT_Data_in_Database#1]
mqtt_Publish_Dummy_Data.py  is working fine, but with mqtt_Listen_Sensor_Data.py I have an issue with on_connect command:

`python mqtt_Listen_Sensor_Data.py
Traceback (most recent call last):
  File "mqtt_Listen_Sensor_Data.py", line 45, in <module>
    mqttc.loop_forever()
  File "/usr/lib/python2.7/site-packages/paho/mqtt/client.py", line 1481, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/lib/python2.7/site-packages/paho/mqtt/client.py", line 1003, in loop
    rc = self.loop_read(max_packets)
  File "/usr/lib/python2.7/site-packages/paho/mqtt/client.py", line 1284, in loop_read
    rc = self._packet_read()
  File "/usr/lib/python2.7/site-packages/paho/mqtt/client.py", line 1849, in _packet_read
    rc = self._packet_handle()
  File "/usr/lib/python2.7/site-packages/paho/mqtt/client.py", line 2311, in _packet_handle
    return self._handle_connack()
  File "/usr/lib/python2.7/site-packages/paho/mqtt/client.py", line 2372, in _handle_connack
    self.on_connect(self, self._userdata, flags_dict, result)
TypeError: on_connect() takes exactly 3 arguments (4 given)`

**Comment by Hecot** [comment]
got it working - just added one argument 

`on_connect(mosq, obj, flags, rc):`

**Comment by linxar109** [comment]
> got it working - just added one argument
> 
> `on_connect(mosq, obj, flags, rc):`

IT works.

**Comment by anitamourya1989** [comment]
Its working
